// 10 topics, 10 challenges each = 100 hands-on MongoDB exercises.
// Each solution is real, runnable MongoDB syntax. The app runs your query and
// the reference solution against the same data and compares the results.
//
// Fields per challenge:
//   id, title, difficulty (1-3), prompt, starter, hints[], solution,
//   explanation, ordered? (true when result order is part of the answer)

export const topics = [
  {
    id: "find-basics",
    name: "1 · Find & Read Basics",
    blurb: "The bread and butter: reading documents with find() and findOne().",
    concept: {
      summary: "Reading documents is the foundation of MongoDB. A filter document decides WHICH documents come back; find() returns a cursor over many matches, findOne() returns a single document (or null).",
      points: [
        "A filter is itself a document: { field: value } keeps docs where field equals value. An empty filter {} matches everything.",
        "Queries are case- and type-sensitive: \"2016\" (string) does not equal 2016 (number).",
        "Querying an array field with a scalar matches if ANY element equals it — no special operator needed.",
        "find() yields a cursor (many docs you can chain .sort/.limit onto); findOne() yields one document or null.",
        "countDocuments(filter) returns a count without transferring the matched documents."
      ],
      syntax: [
        { code: "db.movies.find({})", note: "every document" },
        { code: "db.movies.find({ year: 2016 })", note: "equality filter" },
        { code: "db.movies.findOne({ _id: 5 })", note: "one document by id" },
        { code: "db.movies.countDocuments({ type: \"movie\" })", note: "count matches" }
      ],
      tip: "Think of every read as two questions: 'which documents?' (the filter) and later 'which fields?' (the projection)."
    },
    challenges: [
      { id: "fb1", title: "Return everything", difficulty: 1,
        prompt: "Return every document in the movies collection.",
        starter: "db.movies.find({})",
        hints: ["An empty filter {} matches all documents.", "find({}) returns the whole collection."],
        solution: "db.movies.find({})",
        explanation: "find({}) with an empty filter returns all documents. In the shell you can also write find() with no arguments." },
      { id: "fb2", title: "Match by title", difficulty: 1,
        prompt: "Find the movie whose title is exactly \"Inception\".",
        starter: "db.movies.find({\n\n})",
        hints: ["Equality is written as { field: value }.", "Strings must be quoted."],
        solution: "db.movies.find({ title: \"Inception\" })",
        explanation: "The simplest filter is field-equals-value. { title: \"Inception\" } keeps documents where title equals that string." },
      { id: "fb3", title: "Filter by year", difficulty: 1,
        prompt: "Find all movies released in the year 2016.",
        starter: "db.movies.find({\n\n})",
        hints: ["year is a number — don't quote it.", "{ year: 2016 }"],
        solution: "db.movies.find({ year: 2016 })",
        explanation: "Numeric equality needs no quotes. MongoDB compares the stored value with the literal you provide." },
      { id: "fb4", title: "Only series", difficulty: 1,
        prompt: "Find all documents where type is \"series\".",
        starter: "db.movies.find({\n\n})",
        hints: ["type is a string field.", "{ type: \"series\" }"],
        solution: "db.movies.find({ type: \"series\" })",
        explanation: "Filtering on a low-cardinality field like type is extremely common — it's how you separate kinds of records living in one collection." },
      { id: "fb5", title: "By director", difficulty: 1,
        prompt: "Find every movie directed by \"Christopher Nolan\".",
        starter: "db.movies.find({\n\n})",
        hints: ["Match the director field exactly.", "Spelling and capitalization must match."],
        solution: "db.movies.find({ director: \"Christopher Nolan\" })",
        explanation: "Equality matches are case-sensitive and exact. To match loosely you'd need $regex (a later topic)." },
      { id: "fb6", title: "findOne by id", difficulty: 1,
        prompt: "Use findOne to return the single movie whose _id is 5.",
        starter: "db.movies.findOne({\n\n})",
        hints: ["findOne returns one document (or null), not a cursor.", "{ _id: 5 }"],
        solution: "db.movies.findOne({ _id: 5 })",
        explanation: "findOne returns the first matching document itself, while find returns a cursor over many. Use findOne when you expect exactly one result." },
      { id: "fb7", title: "Value inside an array", difficulty: 2,
        prompt: "Find all movies that list \"Korean\" among their languages.",
        starter: "db.movies.find({\n\n})",
        hints: ["languages is an array.", "Querying an array field for a value matches if any element equals it."],
        solution: "db.movies.find({ languages: \"Korean\" })",
        explanation: "When you query an array field with a scalar, MongoDB matches documents where ANY array element equals that value. No special operator needed." },
      { id: "fb8", title: "Count everything", difficulty: 1,
        prompt: "Return the number of documents in the movies collection (a single number).",
        starter: "db.movies.countDocuments({})",
        hints: ["countDocuments returns a number, not documents.", "Pass an empty filter."],
        solution: "db.movies.countDocuments({})",
        explanation: "countDocuments({}) is the modern, accurate way to count. It accepts the same filter object as find." },
      { id: "fb9", title: "Count with a filter", difficulty: 1,
        prompt: "Count how many users have membership \"premium\".",
        starter: "db.users.countDocuments({\n\n})",
        hints: ["Combine a filter with countDocuments.", "{ membership: \"premium\" }"],
        solution: "db.users.countDocuments({ membership: \"premium\" })",
        explanation: "Counting with a filter avoids pulling documents you only wanted to tally — cheaper and clearer." },
      { id: "fb10", title: "Users by city", difficulty: 1,
        prompt: "Find all users who live in \"Seattle\".",
        starter: "db.users.find({\n\n})",
        hints: ["Switch the collection to users.", "{ city: \"Seattle\" }"],
        solution: "db.users.find({ city: \"Seattle\" })",
        explanation: "The same find patterns work on every collection. Learn them once, apply them everywhere." }
    ]
  },

  {
    id: "operators",
    name: "2 · Query Operators",
    blurb: "Comparison ($gt, $lt, $in…) and logical ($or, $and) operators.",
    concept: {
      summary: "Operators let a filter express far more than equality — ranges, sets, negation, and boolean logic — by nesting an operator object under a field.",
      points: [
        "Comparison operators live in a sub-object: { field: { $gt: value } }.",
        "$gt / $gte / $lt / $lte build ranges; $ne is not-equal; $in / $nin match against a list.",
        "Multiple operators on ONE field are ANDed: { rating: { $gte: 8, $lte: 9 } } is an inclusive range.",
        "Multiple fields in one filter form an implicit AND.",
        "$or / $and / $nor take an ARRAY of full filter documents; use $or for alternatives.",
        "Dot notation (\"awards.wins\") reaches into embedded documents — quote the path."
      ],
      syntax: [
        { code: "{ rating: { $gt: 8.7 } }", note: "greater than" },
        { code: "{ year: { $in: [1994, 1999] } }", note: "one of a set" },
        { code: "{ $or: [ { rating: { $gt: 9 } }, { runtime: { $gt: 160 } } ] }", note: "either condition" },
        { code: "{ \"awards.wins\": { $gte: 100 } }", note: "nested field" }
      ],
      tip: "Prefer $in over a long chain of $or equalities — it is shorter and more index-friendly."
    },
    challenges: [
      { id: "op1", title: "Greater than", difficulty: 1,
        prompt: "Find movies with a rating greater than 8.7.",
        starter: "db.movies.find({ rating: {\n\n} })",
        hints: ["$gt means greater than (strictly).", "{ rating: { $gt: 8.7 } }"],
        solution: "db.movies.find({ rating: { $gt: 8.7 } })",
        explanation: "Comparison operators go inside a sub-object: { field: { $gt: value } }. $gt is exclusive; use $gte to include the boundary." },
      { id: "op2", title: "A closed range", difficulty: 2,
        prompt: "Find movies with a rating from 8.5 to 8.7 inclusive.",
        starter: "db.movies.find({ rating: {\n\n} })",
        hints: ["Combine $gte and $lte in the same sub-object.", "{ rating: { $gte: 8.5, $lte: 8.7 } }"],
        solution: "db.movies.find({ rating: { $gte: 8.5, $lte: 8.7 } })",
        explanation: "Multiple operators on the same field are ANDed together, giving you an inclusive range in one clause." },
      { id: "op3", title: "Before a year", difficulty: 1,
        prompt: "Find movies released before the year 2000.",
        starter: "db.movies.find({ year: {\n\n} })",
        hints: ["$lt means less than.", "{ year: { $lt: 2000 } }"],
        solution: "db.movies.find({ year: { $lt: 2000 } })",
        explanation: "$lt / $lte / $gt / $gte are the four comparison workhorses you'll reach for constantly." },
      { id: "op4", title: "Not equal", difficulty: 1,
        prompt: "Find all documents whose type is NOT \"movie\".",
        starter: "db.movies.find({ type: {\n\n} })",
        hints: ["$ne means not equal.", "{ type: { $ne: \"movie\" } }"],
        solution: "db.movies.find({ type: { $ne: \"movie\" } })",
        explanation: "$ne matches documents where the field differs from the value (and also documents missing the field, in real MongoDB)." },
      { id: "op5", title: "One of several", difficulty: 2,
        prompt: "Find movies whose year is 1994, 1999, or 2019.",
        starter: "db.movies.find({ year: {\n\n} })",
        hints: ["$in takes an array of acceptable values.", "{ year: { $in: [1994, 1999, 2019] } }"],
        solution: "db.movies.find({ year: { $in: [1994, 1999, 2019] } })",
        explanation: "$in is the clean alternative to a long chain of $or equalities." },
      { id: "op6", title: "None of these", difficulty: 2,
        prompt: "Find movies whose director is NOT \"Christopher Nolan\" and NOT \"Damien Chazelle\".",
        starter: "db.movies.find({ director: {\n\n} })",
        hints: ["$nin = not in.", "{ director: { $nin: [\"Christopher Nolan\", \"Damien Chazelle\"] } }"],
        solution: "db.movies.find({ director: { $nin: [\"Christopher Nolan\", \"Damien Chazelle\"] } })",
        explanation: "$nin excludes any document whose field value appears in the list." },
      { id: "op7", title: "Either condition", difficulty: 2,
        prompt: "Find movies where rating is greater than 8.9 OR runtime is greater than 160.",
        starter: "db.movies.find({ $or: [\n\n] })",
        hints: ["$or takes an array of full filter objects.", "Each branch is its own { } condition."],
        solution: "db.movies.find({ $or: [ { rating: { $gt: 8.9 } }, { runtime: { $gt: 160 } } ] })",
        explanation: "$or is a top-level operator whose value is an array of sub-queries. A document matches if any sub-query matches." },
      { id: "op8", title: "Implicit AND", difficulty: 2,
        prompt: "Find movies that are type \"movie\" AND have boxOffice greater than 500.",
        starter: "db.movies.find({\n\n})",
        hints: ["Multiple fields in one filter are ANDed automatically.", "No $and needed here."],
        solution: "db.movies.find({ type: \"movie\", boxOffice: { $gt: 500 } })",
        explanation: "Listing multiple fields in a single filter object is an implicit AND — the most common way to combine conditions." },
      { id: "op9", title: "Age band", difficulty: 1,
        prompt: "Find users whose age is between 25 and 35 inclusive.",
        starter: "db.users.find({ age: {\n\n} })",
        hints: ["Use $gte and $lte together.", "Works on the users collection."],
        solution: "db.users.find({ age: { $gte: 25, $lte: 35 } })",
        explanation: "Ranges apply to any numeric field on any collection — here we switch to users." },
      { id: "op10", title: "Reach into nested fields", difficulty: 2,
        prompt: "Find movies where awards.wins is greater than 150. (awards is an embedded object.)",
        starter: "db.movies.find({\n\n})",
        hints: ["Use dot notation in a quoted key: \"awards.wins\".", "{ \"awards.wins\": { $gt: 150 } }"],
        solution: "db.movies.find({ \"awards.wins\": { $gt: 150 } })",
        explanation: "Dot notation lets you query fields inside embedded documents. The whole path must be quoted because of the dot." }
    ]
  },

  {
    id: "projection",
    name: "3 · Projection",
    blurb: "Shape the output: include or exclude fields with the second argument.",
    concept: {
      summary: "A projection is the second argument to find(). It chooses which fields are returned, keeping payloads small and focused.",
      points: [
        "1 = include, 0 = exclude. You generally cannot mix 1s and 0s in one projection…",
        "…except _id, which you may set to 0 while otherwise using an inclusion projection.",
        "Inclusion projection returns ONLY the listed fields (plus _id unless excluded).",
        "Exclusion projection returns EVERYTHING except the listed fields.",
        "Dot notation projects a nested sub-field: { \"awards.wins\": 1 }."
      ],
      syntax: [
        { code: "db.movies.find({}, { title: 1, year: 1, _id: 0 })", note: "include, drop _id" },
        { code: "db.movies.find({}, { cast: 0, awards: 0 })", note: "exclude fields" },
        { code: "db.movies.find({}, { title: 1, \"awards.wins\": 1, _id: 0 })", note: "nested" }
      ],
      tip: "Return only what the caller needs — smaller documents mean less network/memory and can enable covered queries served entirely from an index."
    },
    challenges: [
      { id: "pr1", title: "Just the title", difficulty: 1,
        prompt: "Return every movie but only the title field (the _id will come along automatically).",
        starter: "db.movies.find({}, {\n\n})",
        hints: ["Projection is the second argument to find.", "{ title: 1 } includes title."],
        solution: "db.movies.find({}, { title: 1 })",
        explanation: "A projection with 1 = include. Only the listed fields (plus _id by default) are returned." },
      { id: "pr2", title: "Drop the _id", difficulty: 1,
        prompt: "Return title and year for all movies, but exclude _id.",
        starter: "db.movies.find({}, {\n\n})",
        hints: ["Set _id: 0 to remove it.", "{ title: 1, year: 1, _id: 0 }"],
        solution: "db.movies.find({}, { title: 1, year: 1, _id: 0 })",
        explanation: "_id is the one field you can exclude while otherwise using an inclusion projection." },
      { id: "pr3", title: "Exclusion projection", difficulty: 2,
        prompt: "Return all movies but hide the cast and awards fields (keep everything else).",
        starter: "db.movies.find({}, {\n\n})",
        hints: ["0 = exclude.", "{ cast: 0, awards: 0 }"],
        solution: "db.movies.find({}, { cast: 0, awards: 0 })",
        explanation: "An exclusion projection returns every field except the ones set to 0. You generally can't mix 1s and 0s (except _id)." },
      { id: "pr4", title: "Filter + project", difficulty: 2,
        prompt: "For Christopher Nolan's movies, return only title and rating (no _id).",
        starter: "db.movies.find({ director: \"Christopher Nolan\" }, {\n\n})",
        hints: ["Filter goes first, projection second.", "{ title: 1, rating: 1, _id: 0 }"],
        solution: "db.movies.find({ director: \"Christopher Nolan\" }, { title: 1, rating: 1, _id: 0 })",
        explanation: "Filtering and projecting are independent: one chooses documents, the other chooses fields." },
      { id: "pr5", title: "Trim the users", difficulty: 1,
        prompt: "Return name and city for all users, excluding _id.",
        starter: "db.users.find({}, {\n\n})",
        hints: ["Same pattern on the users collection.", "{ name: 1, city: 1, _id: 0 }"],
        solution: "db.users.find({}, { name: 1, city: 1, _id: 0 })",
        explanation: "Projection keeps payloads small — return only what the caller needs." },
      { id: "pr6", title: "Project a nested field", difficulty: 3,
        prompt: "Return title and awards.wins for all movies (no _id). Use dot notation in the projection.",
        starter: "db.movies.find({}, {\n\n})",
        hints: ["Quote the dotted path: \"awards.wins\": 1.", "{ title: 1, \"awards.wins\": 1, _id: 0 }"],
        solution: "db.movies.find({}, { title: 1, \"awards.wins\": 1, _id: 0 })",
        explanation: "Dot notation in a projection returns just that sub-field, nested inside its parent object in the output." },
      { id: "pr7", title: "Recent, trimmed", difficulty: 2,
        prompt: "For movies released after 2010, return title and year only (no _id).",
        starter: "db.movies.find({ year: { $gt: 2010 } }, {\n\n})",
        hints: ["Combine a $gt filter with an inclusion projection.", "{ title: 1, year: 1, _id: 0 }"],
        solution: "db.movies.find({ year: { $gt: 2010 } }, { title: 1, year: 1, _id: 0 })",
        explanation: "This is the everyday shape of a read query: pick rows with the filter, pick columns with the projection." },
      { id: "pr8", title: "Only the ids", difficulty: 2,
        prompt: "Return only the _id of each series (type \"series\").",
        starter: "db.movies.find({ type: \"series\" }, {\n\n})",
        hints: ["Include just _id.", "{ _id: 1 }"],
        solution: "db.movies.find({ type: \"series\" }, { _id: 1 })",
        explanation: "Projecting only _id is handy when you just need identifiers to feed another query." },
      { id: "pr9", title: "Premium favorites", difficulty: 2,
        prompt: "For premium users, return name and favorites only (no _id).",
        starter: "db.users.find({ membership: \"premium\" }, {\n\n})",
        hints: ["Array fields can be included like any other.", "{ name: 1, favorites: 1, _id: 0 }"],
        solution: "db.users.find({ membership: \"premium\" }, { name: 1, favorites: 1, _id: 0 })",
        explanation: "Including an array field returns the whole array. (To slice it you'd use $slice.)" },
      { id: "pr10", title: "Slim reviews", difficulty: 1,
        prompt: "Return text and stars for every review, excluding _id.",
        starter: "db.reviews.find({}, {\n\n})",
        hints: ["Work on the reviews collection.", "{ text: 1, stars: 1, _id: 0 }"],
        solution: "db.reviews.find({}, { text: 1, stars: 1, _id: 0 })",
        explanation: "By now the projection pattern should feel automatic across all three collections." }
    ]
  },

  {
    id: "sort-page",
    name: "4 · Sorting & Pagination",
    blurb: "Order results with sort(), page through them with limit() and skip().",
    concept: {
      summary: "Order results with sort(), then window them with skip() and limit(). Together these give you leaderboards and pagination.",
      points: [
        "sort({ field: 1 }) is ascending, -1 is descending.",
        "Compound sorts apply keys left-to-right: { year: -1, title: 1 } (primary key, then tie-breaker).",
        "limit(n) caps the number of results; skip(n) offsets past the first n.",
        "Always sort BEFORE limit to get a real top-N, not an arbitrary slice.",
        "Large skips are slow (the server still walks skipped docs); production apps often paginate with a range filter on an indexed field ('seek' pagination)."
      ],
      syntax: [
        { code: "db.movies.find({}).sort({ rating: -1 }).limit(3)", note: "top 3" },
        { code: "db.movies.find({}).sort({ title: 1 }).skip(5).limit(5)", note: "page 2 of 5" },
        { code: "db.movies.find({}).sort({ year: -1, title: 1 })", note: "compound sort" }
      ],
      tip: "'The best X' = filter to X → sort by the metric → limit(1)."
    },
    challenges: [
      { id: "sp1", title: "Best first", difficulty: 1, ordered: true,
        prompt: "Return all movies sorted by rating, highest first.",
        starter: "db.movies.find({}).sort({\n\n})",
        hints: ["-1 = descending, 1 = ascending.", "{ rating: -1 }"],
        solution: "db.movies.find({}).sort({ rating: -1 })",
        explanation: "sort() takes a spec object; -1 sorts descending. Order matters here, so the sequence is part of the answer." },
      { id: "sp2", title: "Oldest to newest", difficulty: 1, ordered: true,
        prompt: "Return all movies sorted by year, ascending.",
        starter: "db.movies.find({}).sort({\n\n})",
        hints: ["1 = ascending.", "{ year: 1 }"],
        solution: "db.movies.find({}).sort({ year: 1 })",
        explanation: "Ascending is the default direction (1), but always being explicit avoids surprises." },
      { id: "sp3", title: "Top 3", difficulty: 2, ordered: true,
        prompt: "Return the 3 highest-rated movies as title and rating only (no _id).",
        starter: "db.movies.find({}, { title: 1, rating: 1, _id: 0 }).sort({\n\n}).limit()",
        hints: ["Sort by rating -1, then limit(3).", "Projection + sort + limit chain together."],
        solution: "db.movies.find({}, { title: 1, rating: 1, _id: 0 }).sort({ rating: -1 }).limit(3)",
        explanation: "sort() before limit() so you keep the top N, not a random N. The server optimizes this into a top-k operation." },
      { id: "sp4", title: "Three oldest", difficulty: 2, ordered: true,
        prompt: "Return the 3 oldest movies (title and year, no _id).",
        starter: "db.movies.find({}, { title: 1, year: 1, _id: 0 }).sort({\n\n}).limit()",
        hints: ["Ascending year, limit 3.", "{ year: 1 } then .limit(3)"],
        solution: "db.movies.find({}, { title: 1, year: 1, _id: 0 }).sort({ year: 1 }).limit(3)",
        explanation: "Same top-k pattern, just ascending to grab the smallest values." },
      { id: "sp5", title: "Page two", difficulty: 3, ordered: true,
        prompt: "Sort movies by title ascending, then skip the first 5 and return the next 3 (title only, no _id).",
        starter: "db.movies.find({}, { title: 1, _id: 0 }).sort({ title: 1 }).skip().limit()",
        hints: ["skip(5) then limit(3).", "Order the chain: sort → skip → limit."],
        solution: "db.movies.find({}, { title: 1, _id: 0 }).sort({ title: 1 }).skip(5).limit(3)",
        explanation: "skip + limit is classic pagination. Beware: large skips are slow; real apps often paginate by a range filter on an indexed field instead." },
      { id: "sp6", title: "Biggest hits", difficulty: 2, ordered: true,
        prompt: "Return the top 5 movies by boxOffice (title and boxOffice, no _id).",
        starter: "db.movies.find({}, { title: 1, boxOffice: 1, _id: 0 }).sort({\n\n}).limit()",
        hints: ["Sort boxOffice descending.", ".limit(5)"],
        solution: "db.movies.find({}, { title: 1, boxOffice: 1, _id: 0 }).sort({ boxOffice: -1 }).limit(5)",
        explanation: "Leaderboards are just sort-descending-then-limit." },
      { id: "sp7", title: "Tie-breaking sort", difficulty: 3, ordered: true,
        prompt: "Sort all movies by year descending, and for movies in the same year, by title ascending. Return title and year (no _id).",
        starter: "db.movies.find({}, { title: 1, year: 1, _id: 0 }).sort({\n\n})",
        hints: ["A sort spec can have multiple keys.", "{ year: -1, title: 1 } — order of keys matters."],
        solution: "db.movies.find({}, { title: 1, year: 1, _id: 0 }).sort({ year: -1, title: 1 })",
        explanation: "Compound sorts apply keys left to right: primary key first, then the next as a tie-breaker." },
      { id: "sp8", title: "Best series", difficulty: 2, ordered: true,
        prompt: "Return the single highest-rated series (type \"series\") as title and rating (no _id).",
        starter: "db.movies.find({ type: \"series\" }, { title: 1, rating: 1, _id: 0 }).sort({\n\n}).limit()",
        hints: ["Filter to series, sort rating -1, limit 1.", "Combine filter + sort + limit."],
        solution: "db.movies.find({ type: \"series\" }, { title: 1, rating: 1, _id: 0 }).sort({ rating: -1 }).limit(1)",
        explanation: "\"The best X\" = filter to X, sort by the metric, limit(1)." },
      { id: "sp9", title: "Youngest users", difficulty: 1, ordered: true,
        prompt: "Return users sorted by age ascending, showing name and age (no _id).",
        starter: "db.users.find({}, { name: 1, age: 1, _id: 0 }).sort({\n\n})",
        hints: ["{ age: 1 }", "Works on the users collection."],
        solution: "db.users.find({}, { name: 1, age: 1, _id: 0 }).sort({ age: 1 })",
        explanation: "The sort/limit toolkit is collection-agnostic." },
      { id: "sp10", title: "Most liked reviews", difficulty: 2, ordered: true,
        prompt: "Return the top 3 reviews by likes, showing text and likes (no _id).",
        starter: "db.reviews.find({}, { text: 1, likes: 1, _id: 0 }).sort({\n\n}).limit()",
        hints: ["Sort likes descending, limit 3.", "{ likes: -1 }"],
        solution: "db.reviews.find({}, { text: 1, likes: 1, _id: 0 }).sort({ likes: -1 }).limit(3)",
        explanation: "You've now combined filter, projection, sort, skip, and limit — the full read toolkit." }
    ]
  },

  {
    id: "arrays",
    name: "5 · Array Queries",
    blurb: "Query inside arrays with $all, $size, $in, $elemMatch and more.",
    concept: {
      summary: "Arrays are first-class in MongoDB. You can match elements, exact lengths, and combinations without ever unpacking the array.",
      points: [
        "Scalar against an array field: { genres: \"Action\" } matches if ANY element is \"Action\".",
        "$all requires ALL listed values to be present (order-independent, extras allowed).",
        "$in matches if ANY element is in the list (a logical OR over membership).",
        "$size matches an EXACT array length — it cannot be combined with a range.",
        "$elemMatch requires a SINGLE element to satisfy all its conditions together."
      ],
      syntax: [
        { code: "{ genres: { $all: [\"Action\", \"Sci-Fi\"] } }", note: "has all" },
        { code: "{ genres: { $size: 2 } }", note: "exact length" },
        { code: "{ favorites: { $elemMatch: { $gte: 10, $lte: 13 } } }", note: "one element in range" }
      ],
      tip: "When combining lower AND upper bounds on array elements, use $elemMatch — otherwise two different elements can each satisfy one bound and wrongly match."
    },
    challenges: [
      { id: "ar1", title: "Contains a value", difficulty: 1,
        prompt: "Find movies whose genres include \"Action\".",
        starter: "db.movies.find({\n\n})",
        hints: ["Querying an array with a scalar matches any element.", "{ genres: \"Action\" }"],
        solution: "db.movies.find({ genres: \"Action\" })",
        explanation: "A scalar against an array field matches if any element equals it — the simplest array query." },
      { id: "ar2", title: "Has all of these", difficulty: 2,
        prompt: "Find movies whose genres include BOTH \"Action\" and \"Sci-Fi\".",
        starter: "db.movies.find({ genres: {\n\n} })",
        hints: ["$all requires every listed element to be present.", "{ genres: { $all: [\"Action\", \"Sci-Fi\"] } }"],
        solution: "db.movies.find({ genres: { $all: [\"Action\", \"Sci-Fi\"] } })",
        explanation: "$all means \"the array contains all of these\", regardless of order or extra elements." },
      { id: "ar3", title: "Exact length", difficulty: 2,
        prompt: "Find movies that have exactly 2 genres.",
        starter: "db.movies.find({ genres: {\n\n} })",
        hints: ["$size matches arrays of an exact length.", "{ genres: { $size: 2 } }"],
        solution: "db.movies.find({ genres: { $size: 2 } })",
        explanation: "$size matches on exact array length. Note: it can't be combined with a range — it's an exact count only." },
      { id: "ar4", title: "Multilingual", difficulty: 2,
        prompt: "Find movies whose languages include both \"English\" and \"Japanese\".",
        starter: "db.movies.find({ languages: {\n\n} })",
        hints: ["$all again, on the languages array.", "{ languages: { $all: [\"English\", \"Japanese\"] } }"],
        solution: "db.movies.find({ languages: { $all: [\"English\", \"Japanese\"] } })",
        explanation: "$all works on any array field — here it finds bilingual films." },
      { id: "ar5", title: "Any of these genres", difficulty: 2,
        prompt: "Find movies whose genres include \"Horror\" or \"Fantasy\".",
        starter: "db.movies.find({ genres: {\n\n} })",
        hints: ["$in checks whether any array element is in the list.", "{ genres: { $in: [\"Horror\", \"Fantasy\"] } }"],
        solution: "db.movies.find({ genres: { $in: [\"Horror\", \"Fantasy\"] } })",
        explanation: "Against an array field, $in matches if any element appears in the list — a logical OR over array membership." },
      { id: "ar6", title: "Empty arrays", difficulty: 2,
        prompt: "Find users whose favorites array is empty.",
        starter: "db.users.find({ favorites: {\n\n} })",
        hints: ["An empty array has size 0.", "{ favorites: { $size: 0 } }"],
        solution: "db.users.find({ favorites: { $size: 0 } })",
        explanation: "$size: 0 is the idiomatic way to find documents with an empty array." },
      { id: "ar7", title: "Favorited a movie", difficulty: 1,
        prompt: "Find users who have movie 5 in their favorites.",
        starter: "db.users.find({\n\n})",
        hints: ["favorites is an array of numbers.", "{ favorites: 5 }"],
        solution: "db.users.find({ favorites: 5 })",
        explanation: "Scalar-against-array membership works for numbers just as it does for strings." },
      { id: "ar8", title: "Tagged classic", difficulty: 1,
        prompt: "Find reviews tagged \"classic\".",
        starter: "db.reviews.find({\n\n})",
        hints: ["tags is an array on reviews.", "{ tags: \"classic\" }"],
        solution: "db.reviews.find({ tags: \"classic\" })",
        explanation: "Same membership pattern on the reviews collection's tags array." },
      { id: "ar9", title: "Untagged reviews", difficulty: 2,
        prompt: "Find reviews that have no tags (empty tags array).",
        starter: "db.reviews.find({ tags: {\n\n} })",
        hints: ["$size: 0 for empty arrays.", "{ tags: { $size: 0 } }"],
        solution: "db.reviews.find({ tags: { $size: 0 } })",
        explanation: "Detecting empty arrays is common when cleaning or validating data." },
      { id: "ar10", title: "Element matching a range", difficulty: 3,
        prompt: "Find users who have at least one favorite whose id is between 10 and 13 inclusive. Use $elemMatch.",
        starter: "db.users.find({ favorites: { $elemMatch: {\n\n} } })",
        hints: ["$elemMatch tests a single element against multiple conditions.", "{ $gte: 10, $lte: 13 }"],
        solution: "db.users.find({ favorites: { $elemMatch: { $gte: 10, $lte: 13 } } })",
        explanation: "$elemMatch requires ONE array element to satisfy all the conditions together — crucial when combining ranges, so the low and high bounds aren't matched by different elements." }
    ]
  },

  {
    id: "agg-shape",
    name: "6 · Aggregation: Match & Shape",
    blurb: "The pipeline mindset: $match to filter, $project to reshape.",
    concept: {
      summary: "The aggregation pipeline is an array of stages; documents flow through them top to bottom, each stage transforming the stream. Start with $match (filter) and $project (reshape).",
      points: [
        "A pipeline is [ {stage}, {stage}, … ]; order matters.",
        "$match uses the SAME operators as find — put it first so later stages process fewer docs.",
        "$project reshapes: include/exclude, rename (name: \"$title\"), or compute new fields.",
        "Inside expressions, reference a field's value with a $ prefix: \"$runtime\".",
        "Expression operators ($add, $divide, $arrayElemAt, comparison ops…) build computed values.",
        "$count collapses the whole stream into one { name: N } document."
      ],
      syntax: [
        { code: "[ { $match: { genres: \"Sci-Fi\" } }, { $project: { _id: 0, title: 1 } } ]", note: "filter then shape" },
        { code: "{ $project: { title: 1, hours: { $divide: [\"$runtime\", 60] } } }", note: "computed field" },
        { code: "{ $project: { title: 1, isHit: { $gt: [\"$boxOffice\", 500] } } }", note: "boolean expression" }
      ],
      tip: "$gt has two forms: as a QUERY operator { field: { $gt: v } } it filters; as an EXPRESSION { $gt: [a, b] } it returns a boolean value."
    },
    challenges: [
      { id: "as1", title: "First pipeline", difficulty: 1,
        prompt: "Using aggregation, return only the title of every Sci-Fi movie (no _id).",
        starter: "db.movies.aggregate([\n  { $match: { genres: \"Sci-Fi\" } },\n  { $project: {  } }\n])",
        hints: ["$match is like find's filter.", "$project: { _id: 0, title: 1 }"],
        solution: "db.movies.aggregate([ { $match: { genres: \"Sci-Fi\" } }, { $project: { _id: 0, title: 1 } } ])",
        explanation: "A pipeline is an array of stages; each stage transforms the stream of documents. $match filters, $project reshapes." },
      { id: "as2", title: "Match then project", difficulty: 2,
        prompt: "Return title and year of movies released after 2010 (no _id), using aggregation.",
        starter: "db.movies.aggregate([\n  { $match: {  } },\n  { $project: {  } }\n])",
        hints: ["$match uses the same operators as find.", "{ year: { $gt: 2010 } } then project title & year."],
        solution: "db.movies.aggregate([ { $match: { year: { $gt: 2010 } } }, { $project: { _id: 0, title: 1, year: 1 } } ])",
        explanation: "$match should come early so later stages process fewer documents — put your filters first." },
      { id: "as3", title: "Computed field: hours", difficulty: 2,
        prompt: "For every movie, return title and a computed field \"hours\" equal to runtime divided by 60 (no _id).",
        starter: "db.movies.aggregate([\n  { $project: { _id: 0, title: 1, hours: {  } } }\n])",
        hints: ["Use the $divide expression: { $divide: [\"$runtime\", 60] }.", "Field references start with $."],
        solution: "db.movies.aggregate([ { $project: { _id: 0, title: 1, hours: { $divide: [\"$runtime\", 60] } } } ])",
        explanation: "In $project you can build new fields from expressions. \"$runtime\" references the field's value; $divide computes with it." },
      { id: "as4", title: "Add two fields", difficulty: 2,
        prompt: "Return title and a computed \"totalAwards\" = awards.wins + awards.nominations, for every movie (no _id).",
        starter: "db.movies.aggregate([\n  { $project: { _id: 0, title: 1, totalAwards: {  } } }\n])",
        hints: ["$add sums values.", "{ $add: [\"$awards.wins\", \"$awards.nominations\"] }"],
        solution: "db.movies.aggregate([ { $project: { _id: 0, title: 1, totalAwards: { $add: [\"$awards.wins\", \"$awards.nominations\"] } } } ])",
        explanation: "Expressions can reach into nested fields with dot notation just like queries." },
      { id: "as5", title: "Boolean expression", difficulty: 3,
        prompt: "Return title and \"isHit\" (true if boxOffice > 500, else false) for every movie (no _id).",
        starter: "db.movies.aggregate([\n  { $project: { _id: 0, title: 1, isHit: {  } } }\n])",
        hints: ["A comparison expression returns a boolean.", "{ $gt: [\"$boxOffice\", 500] }"],
        solution: "db.movies.aggregate([ { $project: { _id: 0, title: 1, isHit: { $gt: [\"$boxOffice\", 500] } } } ])",
        explanation: "As an expression (array form), $gt returns a boolean you can store in a field — different from the query-operator form." },
      { id: "as6", title: "First genre", difficulty: 3,
        prompt: "Return title and \"mainGenre\" (the first element of genres) for every movie (no _id).",
        starter: "db.movies.aggregate([\n  { $project: { _id: 0, title: 1, mainGenre: {  } } }\n])",
        hints: ["$arrayElemAt picks an element by index.", "{ $arrayElemAt: [\"$genres\", 0] }"],
        solution: "db.movies.aggregate([ { $project: { _id: 0, title: 1, mainGenre: { $arrayElemAt: [\"$genres\", 0] } } } ])",
        explanation: "$arrayElemAt: [array, index] extracts one element. Index 0 is the first; negative indexes count from the end." },
      { id: "as7", title: "Just series titles", difficulty: 1,
        prompt: "Using aggregation, return the title of every series (type \"series\"), no _id.",
        starter: "db.movies.aggregate([\n  { $match: {  } },\n  { $project: {  } }\n])",
        hints: ["Match type series.", "Project title only, drop _id."],
        solution: "db.movies.aggregate([ { $match: { type: \"series\" } }, { $project: { _id: 0, title: 1 } } ])",
        explanation: "Everything you can do with find({...}, {...}) you can also express as $match + $project." },
      { id: "as8", title: "Count with a stage", difficulty: 2,
        prompt: "Count how many movies were released after 2010 using a $count stage. Name the output field \"total\".",
        starter: "db.movies.aggregate([\n  { $match: {  } },\n  { $count: \"total\" }\n])",
        hints: ["$count outputs a single document { total: N }.", "Match year > 2010 first."],
        solution: "db.movies.aggregate([ { $match: { year: { $gt: 2010 } } }, { $count: \"total\" } ])",
        explanation: "$count collapses the stream to one document with the count under the name you give it." },
      { id: "as9", title: "Rename via projection", difficulty: 2,
        prompt: "For every movie return \"name\" (the title) and \"score\" (the rating), no _id.",
        starter: "db.movies.aggregate([\n  { $project: {  } }\n])",
        hints: ["Assign a field to another field's value: name: \"$title\".", "score: \"$rating\""],
        solution: "db.movies.aggregate([ { $project: { _id: 0, name: \"$title\", score: \"$rating\" } } ])",
        explanation: "Setting a new key to \"$otherField\" renames/copies it in the output — a projection can rename fields." },
      { id: "as10", title: "Match, sort, project", difficulty: 2, ordered: true,
        prompt: "For Christopher Nolan's movies, return title and rating (no _id), sorted by rating descending — all inside the pipeline.",
        starter: "db.movies.aggregate([\n  { $match: {  } },\n  { $sort: {  } },\n  { $project: {  } }\n])",
        hints: ["$sort is a pipeline stage too.", "Match director, sort rating -1, project title & rating."],
        solution: "db.movies.aggregate([ { $match: { director: \"Christopher Nolan\" } }, { $sort: { rating: -1 } }, { $project: { _id: 0, title: 1, rating: 1 } } ])",
        explanation: "Stage order matters: match to shrink, sort to order, project to shape. This mirrors a find with filter+sort+projection." }
    ]
  },

  {
    id: "agg-group",
    name: "7 · Aggregation: Grouping",
    blurb: "$group and accumulators ($sum, $avg, $min, $max, $push).",
    concept: {
      summary: "$group buckets documents by a key and computes accumulated values per bucket — MongoDB's answer to SQL GROUP BY.",
      points: [
        "_id is the group key: \"$field\" groups by that field; _id: null groups everything into one bucket.",
        "Accumulators: $sum, $avg, $min, $max, $push, $addToSet, $first, $last.",
        "{ $sum: 1 } counts documents; { $sum: \"$field\" } totals a numeric field.",
        "$push collects values into an array; $addToSet collects only DISTINCT values.",
        "Group output order is NOT guaranteed — add a $sort stage for deterministic results."
      ],
      syntax: [
        { code: "[ { $group: { _id: \"$type\", count: { $sum: 1 } } } ]", note: "count per key" },
        { code: "[ { $group: { _id: \"$director\", total: { $sum: \"$boxOffice\" } } }, { $sort: { total: -1 } } ]", note: "sum + rank" },
        { code: "[ { $group: { _id: null, avgRating: { $avg: \"$rating\" } } } ]", note: "overall stat" }
      ],
      tip: "A $match placed AFTER $group filters on aggregated values — this is the equivalent of SQL's HAVING clause."
    },
    challenges: [
      { id: "gr1", title: "Count per type", difficulty: 2, ordered: true,
        prompt: "Count how many documents exist per type. Output { _id, count }, sorted by _id ascending.",
        starter: "db.movies.aggregate([\n  { $group: { _id: \"$type\", count: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["Group by \"$type\".", "count: { $sum: 1 } counts documents."],
        solution: "db.movies.aggregate([ { $group: { _id: \"$type\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ])",
        explanation: "$group's _id is the key you group by. { $sum: 1 } adds one per document — a count. We sort because group output order isn't guaranteed." },
      { id: "gr2", title: "Average rating per type", difficulty: 2, ordered: true,
        prompt: "For each type, compute the average rating as \"avgRating\". Sort by _id ascending.",
        starter: "db.movies.aggregate([\n  { $group: { _id: \"$type\", avgRating: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$avg over the field: { $avg: \"$rating\" }.", "Group key is \"$type\"."],
        solution: "db.movies.aggregate([ { $group: { _id: \"$type\", avgRating: { $avg: \"$rating\" } } }, { $sort: { _id: 1 } } ])",
        explanation: "$avg is an accumulator: it averages the referenced field across each group." },
      { id: "gr3", title: "Users per city", difficulty: 2, ordered: true,
        prompt: "Count users per city. Output { _id, count } sorted by _id ascending.",
        starter: "db.users.aggregate([\n  { $group: {  } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["Group by \"$city\", count with $sum: 1.", "Sort by _id."],
        solution: "db.users.aggregate([ { $group: { _id: \"$city\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ])",
        explanation: "Grouping is how you build breakdowns and histograms from raw documents." },
      { id: "gr4", title: "Top directors by revenue", difficulty: 3, ordered: true,
        prompt: "Sum boxOffice per director as \"total\", then return the top 5 directors by total (sorted by total descending).",
        starter: "db.movies.aggregate([\n  { $group: { _id: \"$director\", total: {  } } },\n  { $sort: {  } },\n  { $limit: 5 }\n])",
        hints: ["$sum over a field adds the values: { $sum: \"$boxOffice\" }.", "Sort total: -1, then $limit: 5."],
        solution: "db.movies.aggregate([ { $group: { _id: \"$director\", total: { $sum: \"$boxOffice\" } } }, { $sort: { total: -1 } }, { $limit: 5 } ])",
        explanation: "{ $sum: \"$field\" } totals a numeric field per group. Follow with sort+limit for a leaderboard." },
      { id: "gr5", title: "Best film per director", difficulty: 3, ordered: true,
        prompt: "For each director, find their maximum movie rating as \"maxRating\". Sort by _id ascending.",
        starter: "db.movies.aggregate([\n  { $group: { _id: \"$director\", maxRating: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$max: \"$rating\".", "Group by director."],
        solution: "db.movies.aggregate([ { $group: { _id: \"$director\", maxRating: { $max: \"$rating\" } } }, { $sort: { _id: 1 } } ])",
        explanation: "$max (and $min) track the extreme value of a field within each group." },
      { id: "gr6", title: "Reviews per movie", difficulty: 2, ordered: true,
        prompt: "Count how many reviews each movie has. Group reviews by movie_id, output { _id, count }, sort by _id ascending.",
        starter: "db.reviews.aggregate([\n  { $group: {  } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["Group by \"$movie_id\".", "count: { $sum: 1 }"],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$movie_id\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ])",
        explanation: "Aggregating a child collection by a foreign key is how you compute per-parent counts." },
      { id: "gr7", title: "Average stars per movie", difficulty: 2, ordered: true,
        prompt: "For each movie_id in reviews, compute the average stars as \"avgStars\". Sort by _id ascending.",
        starter: "db.reviews.aggregate([\n  { $group: { _id: \"$movie_id\", avgStars: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$avg: \"$stars\".", "Group by movie_id."],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$movie_id\", avgStars: { $avg: \"$stars\" } } }, { $sort: { _id: 1 } } ])",
        explanation: "Per-key averages are a core reporting pattern — ratings, prices, response times, etc." },
      { id: "gr8", title: "Grand totals", difficulty: 2,
        prompt: "Across ALL movies, compute count as \"count\" and average rating as \"avgRating\". Use _id: null.",
        starter: "db.movies.aggregate([\n  { $group: { _id: null,  } }\n])",
        hints: ["_id: null groups everything into one bucket.", "count: { $sum: 1 }, avgRating: { $avg: \"$rating\" }"],
        solution: "db.movies.aggregate([ { $group: { _id: null, count: { $sum: 1 }, avgRating: { $avg: \"$rating\" } } } ])",
        explanation: "_id: null collapses the whole collection into a single group for overall statistics." },
      { id: "gr9", title: "Collect titles", difficulty: 3, ordered: true,
        prompt: "For each director, collect their movie titles into an array called \"titles\". Sort by _id ascending.",
        starter: "db.movies.aggregate([\n  { $group: { _id: \"$director\", titles: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$push accumulates values into an array.", "{ $push: \"$title\" }"],
        solution: "db.movies.aggregate([ { $group: { _id: \"$director\", titles: { $push: \"$title\" } } }, { $sort: { _id: 1 } } ])",
        explanation: "$push gathers a value from every document in the group into an array — great for rolling children up under a key." },
      { id: "gr10", title: "Oldest and newest", difficulty: 2,
        prompt: "Across all movies, return the earliest year as \"oldest\" and the latest as \"newest\" (use _id: null).",
        starter: "db.movies.aggregate([\n  { $group: { _id: null, oldest: {  }, newest: {  } } }\n])",
        hints: ["$min and $max on \"$year\".", "_id: null for a single overall group."],
        solution: "db.movies.aggregate([ { $group: { _id: null, oldest: { $min: \"$year\" }, newest: { $max: \"$year\" } } } ])",
        explanation: "$min and $max in the same group give you the full range in one pass." }
    ]
  },

  {
    id: "agg-unwind",
    name: "8 · Aggregation: Unwinding Arrays",
    blurb: "$unwind flattens arrays so you can group and count their elements.",
    concept: {
      summary: "$unwind expands an array field into one document per element, so you can then group, count, and aggregate the contents.",
      points: [
        "$unwind: \"$genres\" outputs one copy of the doc per genre, each still carrying the other fields.",
        "Empty or missing arrays are DROPPED by default (use { path, preserveNullAndEmptyArrays: true } to keep them).",
        "The classic recipe is $unwind → $group to tally per element.",
        "Because one document contributes to several elements, sums (e.g. revenue) can exceed the raw total.",
        "A two-stage group (dedupe with the first, count with the second) counts distinct values."
      ],
      syntax: [
        { code: "[ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } } ]", note: "count per element" },
        { code: "[ { $unwind: \"$genres\" }, { $count: \"genreTags\" } ]", note: "total elements" }
      ],
      tip: "Add an _id tie-breaker to $sort (e.g. { count: -1, _id: 1 }) so records with equal counts come back in a stable order."
    },
    challenges: [
      { id: "un1", title: "Movies per genre", difficulty: 2, ordered: true,
        prompt: "Count how many movies fall under each genre. Unwind genres, group by genre, sort by count descending then _id ascending.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $group: {  } },\n  { $sort: { count: -1, _id: 1 } }\n])",
        hints: ["After $unwind, \"$genres\" is a single string per document.", "Group _id: \"$genres\", count: { $sum: 1 }."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } } ])",
        explanation: "$unwind outputs one document per array element. Grouping afterward turns array contents into per-value counts. The _id tie-breaker makes ordering deterministic." },
      { id: "un2", title: "Rating per genre", difficulty: 3, ordered: true,
        prompt: "Compute the average rating per genre as \"avgRating\". Unwind genres, group, sort by _id ascending.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $group: { _id: \"$genres\", avgRating: {  } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$avg: \"$rating\" after unwinding.", "Each unwound doc keeps the parent's rating."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\", avgRating: { $avg: \"$rating\" } } }, { $sort: { _id: 1 } } ])",
        explanation: "After $unwind, each copy still carries the other fields (like rating), so accumulators work per element." },
      { id: "un3", title: "Movies per language", difficulty: 2, ordered: true,
        prompt: "Count movies per language. Unwind languages, group, sort by count descending then _id ascending.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$languages\" },\n  { $group: {  } },\n  { $sort: { count: -1, _id: 1 } }\n])",
        hints: ["Unwind \"$languages\".", "Group _id: \"$languages\"."],
        solution: "db.movies.aggregate([ { $unwind: \"$languages\" }, { $group: { _id: \"$languages\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } } ])",
        explanation: "The unwind-then-group recipe works on any array field." },
      { id: "un4", title: "Movies per country", difficulty: 2, ordered: true,
        prompt: "Count movies per country. Unwind countries, group, sort by _id ascending.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$countries\" },\n  { $group: {  } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["Unwind \"$countries\", group by it.", "count: { $sum: 1 }"],
        solution: "db.movies.aggregate([ { $unwind: \"$countries\" }, { $group: { _id: \"$countries\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ])",
        explanation: "Co-productions (multiple countries) get counted once per country — exactly what unwind enables." },
      { id: "un5", title: "Tag popularity", difficulty: 2, ordered: true,
        prompt: "Count how often each review tag appears. Unwind tags, group, sort by count descending then _id ascending.",
        starter: "db.reviews.aggregate([\n  { $unwind: \"$tags\" },\n  { $group: {  } },\n  { $sort: { count: -1, _id: 1 } }\n])",
        hints: ["Empty tag arrays simply drop out during unwind.", "Group _id: \"$tags\"."],
        solution: "db.reviews.aggregate([ { $unwind: \"$tags\" }, { $group: { _id: \"$tags\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } } ])",
        explanation: "By default $unwind removes documents whose array is empty or missing — those reviews contribute no tags." },
      { id: "un6", title: "Most favorited movies", difficulty: 3, ordered: true,
        prompt: "From users, count how many times each movie id appears in favorites. Unwind favorites, group, sort by count descending then _id ascending, and return the top 5.",
        starter: "db.users.aggregate([\n  { $unwind: \"$favorites\" },\n  { $group: {  } },\n  { $sort: { count: -1, _id: 1 } },\n  { $limit: 5 }\n])",
        hints: ["Unwind \"$favorites\" (an array of ids).", "Group _id: \"$favorites\"."],
        solution: "db.users.aggregate([ { $unwind: \"$favorites\" }, { $group: { _id: \"$favorites\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }, { $limit: 5 } ])",
        explanation: "Unwinding a numeric array works identically to a string array — great for tallying references." },
      { id: "un7", title: "Animation titles", difficulty: 3, ordered: true,
        prompt: "List the titles of all Animation movies. Unwind genres, match \"Animation\", project title (no _id), sort by title ascending.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $match: {  } },\n  { $project: {  } },\n  { $sort: { title: 1 } }\n])",
        hints: ["After unwind, match genres: \"Animation\".", "Project title, drop _id."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $match: { genres: \"Animation\" } }, { $project: { _id: 0, title: 1 } }, { $sort: { title: 1 } } ])",
        explanation: "Matching after unwind filters on a single element value. Each movie has unique genres, so no duplicates appear here." },
      { id: "un8", title: "Revenue by genre", difficulty: 3, ordered: true,
        prompt: "Sum boxOffice per genre as \"total\". Unwind genres, group, sort by total descending then _id ascending, return top 5.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $group: { _id: \"$genres\", total: {  } } },\n  { $sort: { total: -1, _id: 1 } },\n  { $limit: 5 }\n])",
        hints: ["$sum: \"$boxOffice\" per genre.", "A movie's revenue is counted under each of its genres."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\", total: { $sum: \"$boxOffice\" } } }, { $sort: { total: -1, _id: 1 } }, { $limit: 5 } ])",
        explanation: "Because one film contributes to several genres, unwind-then-sum can exceed the raw total — that's expected with overlapping categories." },
      { id: "un9", title: "Total genre tags", difficulty: 2,
        prompt: "Count the total number of genre entries across all movies (sum of all genres array lengths). Unwind genres then use $count named \"genreTags\".",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $count: \"genreTags\" }\n])",
        hints: ["Each unwound document is one genre entry.", "$count tallies the stream."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $count: \"genreTags\" } ])",
        explanation: "Unwind explodes every element into its own document, so a plain $count gives the total number of array entries." },
      { id: "un10", title: "How many distinct genres", difficulty: 3,
        prompt: "Count the number of DISTINCT genres. Unwind genres, group by genre to dedupe, then group again with _id: null and count as \"distinctGenres\".",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $group: { _id: \"$genres\" } },\n  { $group: { _id: null, distinctGenres: {  } } }\n])",
        hints: ["First group collapses duplicates into one doc per genre.", "Second group counts those docs: { $sum: 1 }."],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\" } }, { $group: { _id: null, distinctGenres: { $sum: 1 } } } ])",
        explanation: "A two-stage group is a powerful idiom: the first deduplicates, the second counts the distinct keys." }
    ]
  },

  {
    id: "agg-lookup",
    name: "9 · Aggregation: Joins ($lookup)",
    blurb: "Relate collections with $lookup, then flatten with $unwind.",
    concept: {
      summary: "$lookup is a left outer join: it pulls matching documents from another collection into a new array field on each input document.",
      points: [
        "Four fields: from (target collection), localField, foreignField, as (output array name).",
        "The result is ALWAYS an array — $unwind it to flatten a one-to-one join into flat fields.",
        "localField can be an array: each element is matched — ideal for arrays of references.",
        "Unmatched parents get an EMPTY array — filter { as: { $size: 0 } } to find orphans.",
        "Reduce first (match / group / limit), THEN join the survivors — joins are expensive.",
        "$size of the joined array gives a related-count without a separate $group."
      ],
      syntax: [
        { code: "{ $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } }", note: "the join" },
        { code: "{ $unwind: \"$movie\" }", note: "flatten to one doc" },
        { code: "{ $project: { title: \"$movie.title\", stars: 1, _id: 0 } }", note: "pull joined fields" }
      ],
      tip: "After $unwind you can $match on joined fields (e.g. \"user.membership\": \"premium\") to filter parents by a property of the joined child."
    },
    challenges: [
      { id: "lk1", title: "Enrich one review", difficulty: 2,
        prompt: "For review _id 1001, join its movie and return { stars, title } where title is the movie's title. (Hint: $lookup gives an array — $unwind it, then project title: \"$movie.title\".)",
        starter: "db.reviews.aggregate([\n  { $match: { _id: 1001 } },\n  { $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } },\n  { $unwind: \"$movie\" },\n  { $project: {  } }\n])",
        hints: ["$lookup adds an array field \"movie\".", "$unwind \"$movie\", then project stars and title: \"$movie.title\", _id: 0."],
        solution: "db.reviews.aggregate([ { $match: { _id: 1001 } }, { $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } }, { $unwind: \"$movie\" }, { $project: { _id: 0, stars: 1, title: \"$movie.title\" } } ])",
        explanation: "$lookup performs a left outer join, adding matches as an array. Unwinding that array turns a one-to-one join into a flat document." },
      { id: "lk2", title: "One user's reviews", difficulty: 3, ordered: true,
        prompt: "For reviews by user_id 101, return { title, stars } (title from the joined movie), sorted by title ascending.",
        starter: "db.reviews.aggregate([\n  { $match: { user_id: 101 } },\n  { $lookup: {  } },\n  { $unwind: \"$movie\" },\n  { $project: {  } },\n  { $sort: { title: 1 } }\n])",
        hints: ["Lookup movies on movie_id = _id, as \"movie\".", "Project title: \"$movie.title\", stars: 1, _id: 0."],
        solution: "db.reviews.aggregate([ { $match: { user_id: 101 } }, { $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } }, { $unwind: \"$movie\" }, { $project: { _id: 0, title: \"$movie.title\", stars: 1 } }, { $sort: { title: 1 } } ])",
        explanation: "Filtering before the join keeps it cheap. The join + unwind + project pattern is the standard way to denormalize on read." },
      { id: "lk3", title: "Reviews with reviewer name", difficulty: 3, ordered: true,
        prompt: "For reviews of movie_id 5, return { name, stars } where name is the reviewer's name (join users), sorted by name ascending.",
        starter: "db.reviews.aggregate([\n  { $match: { movie_id: 5 } },\n  { $lookup: { from: \"users\", localField: \"user_id\", foreignField: \"_id\", as: \"user\" } },\n  { $unwind: \"$user\" },\n  { $project: {  } },\n  { $sort: { name: 1 } }\n])",
        hints: ["Join users on user_id = _id.", "Project name: \"$user.name\", stars: 1, _id: 0."],
        solution: "db.reviews.aggregate([ { $match: { movie_id: 5 } }, { $lookup: { from: \"users\", localField: \"user_id\", foreignField: \"_id\", as: \"user\" } }, { $unwind: \"$user\" }, { $project: { _id: 0, name: \"$user.name\", stars: 1 } }, { $sort: { name: 1 } } ])",
        explanation: "$lookup can target any collection — here we join reviews to users to attach reviewer names." },
      { id: "lk4", title: "Review counts on movies", difficulty: 3, ordered: true,
        prompt: "For each movie, return { title, reviewCount } where reviewCount is how many reviews reference it. Join reviews into movies, count with $size, sort by reviewCount descending then title ascending, top 5.",
        starter: "db.movies.aggregate([\n  { $lookup: { from: \"reviews\", localField: \"_id\", foreignField: \"movie_id\", as: \"reviews\" } },\n  { $project: { _id: 0, title: 1, reviewCount: {  } } },\n  { $sort: { reviewCount: -1, title: 1 } },\n  { $limit: 5 }\n])",
        hints: ["This is a reverse join: match movie._id to reviews.movie_id.", "reviewCount: { $size: \"$reviews\" }"],
        solution: "db.movies.aggregate([ { $lookup: { from: \"reviews\", localField: \"_id\", foreignField: \"movie_id\", as: \"reviews\" } }, { $project: { _id: 0, title: 1, reviewCount: { $size: \"$reviews\" } } }, { $sort: { reviewCount: -1, title: 1 } }, { $limit: 5 } ])",
        explanation: "Joining children into the parent and taking $size of the array is the idiomatic way to compute counts without a separate group." },
      { id: "lk5", title: "Resolve one user's favorites", difficulty: 3,
        prompt: "For user _id 101, return { name, favCount } where favCount is how many of their favorites resolve to real movies. Join movies where favorites contains _id.",
        starter: "db.users.aggregate([\n  { $match: { _id: 101 } },\n  { $lookup: { from: \"movies\", localField: \"favorites\", foreignField: \"_id\", as: \"favMovies\" } },\n  { $project: { _id: 0, name: 1, favCount: {  } } }\n])",
        hints: ["localField can be an array — each element is matched.", "favCount: { $size: \"$favMovies\" }"],
        solution: "db.users.aggregate([ { $match: { _id: 101 } }, { $lookup: { from: \"movies\", localField: \"favorites\", foreignField: \"_id\", as: \"favMovies\" } }, { $project: { _id: 0, name: 1, favCount: { $size: \"$favMovies\" } } } ])",
        explanation: "When localField is an array, $lookup matches on any element — perfect for resolving arrays of references." },
      { id: "lk6", title: "Movies with zero reviews", difficulty: 3, ordered: true,
        prompt: "Find movies that have no reviews. Join reviews into movies, keep those with an empty reviews array, return title (no _id), sorted by title ascending.",
        starter: "db.movies.aggregate([\n  { $lookup: { from: \"reviews\", localField: \"_id\", foreignField: \"movie_id\", as: \"reviews\" } },\n  { $match: { reviews: { $size: 0 } } },\n  { $project: {  } },\n  { $sort: { title: 1 } }\n])",
        hints: ["After the join, filter reviews: { $size: 0 }.", "Project title only."],
        solution: "db.movies.aggregate([ { $lookup: { from: \"reviews\", localField: \"_id\", foreignField: \"movie_id\", as: \"reviews\" } }, { $match: { reviews: { $size: 0 } } }, { $project: { _id: 0, title: 1 } }, { $sort: { title: 1 } } ])",
        explanation: "Because $lookup is a left outer join, unmatched parents get an empty array — filtering on $size: 0 finds the orphans." },
      { id: "lk7", title: "Two joins at once", difficulty: 3,
        prompt: "For review _id 1004, return { title, reviewer, stars } — title from movies, reviewer from the user's name. Do two lookups.",
        starter: "db.reviews.aggregate([\n  { $match: { _id: 1004 } },\n  { $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } },\n  { $lookup: { from: \"users\", localField: \"user_id\", foreignField: \"_id\", as: \"user\" } },\n  { $unwind: \"$movie\" },\n  { $unwind: \"$user\" },\n  { $project: {  } }\n])",
        hints: ["Chain two $lookup stages.", "Project title: \"$movie.title\", reviewer: \"$user.name\", stars: 1, _id: 0."],
        solution: "db.reviews.aggregate([ { $match: { _id: 1004 } }, { $lookup: { from: \"movies\", localField: \"movie_id\", foreignField: \"_id\", as: \"movie\" } }, { $lookup: { from: \"users\", localField: \"user_id\", foreignField: \"_id\", as: \"user\" } }, { $unwind: \"$movie\" }, { $unwind: \"$user\" }, { $project: { _id: 0, title: \"$movie.title\", reviewer: \"$user.name\", stars: 1 } } ])",
        explanation: "You can perform multiple joins in one pipeline. Each $lookup adds its own array; unwind each to flatten." },
      { id: "lk8", title: "Average stars per movie title", difficulty: 3, ordered: true,
        prompt: "Compute average stars per movie, showing the movie TITLE. Group reviews by movie_id (avgStars), join movies for the title, project { title, avgStars }, sort by avgStars descending then title ascending, top 5.",
        starter: "db.reviews.aggregate([\n  { $group: { _id: \"$movie_id\", avgStars: { $avg: \"$stars\" } } },\n  { $lookup: { from: \"movies\", localField: \"_id\", foreignField: \"_id\", as: \"movie\" } },\n  { $unwind: \"$movie\" },\n  { $project: {  } },\n  { $sort: { avgStars: -1, title: 1 } },\n  { $limit: 5 }\n])",
        hints: ["Group first, then join the grouped _id (movie_id) to movies._id.", "Project title: \"$movie.title\", avgStars: 1, _id: 0."],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$movie_id\", avgStars: { $avg: \"$stars\" } } }, { $lookup: { from: \"movies\", localField: \"_id\", foreignField: \"_id\", as: \"movie\" } }, { $unwind: \"$movie\" }, { $project: { _id: 0, title: \"$movie.title\", avgStars: 1 } }, { $sort: { avgStars: -1, title: 1 } }, { $limit: 5 } ])",
        explanation: "A common real pattern: aggregate the fact table, then join a dimension table to attach human-readable labels." },
      { id: "lk9", title: "Top reviewer", difficulty: 3,
        prompt: "Find the user who wrote the most reviews and return { name, count }. Group reviews by user_id, sort by count desc (tie-break _id asc), take 1, join users for the name.",
        starter: "db.reviews.aggregate([\n  { $group: { _id: \"$user_id\", count: { $sum: 1 } } },\n  { $sort: { count: -1, _id: 1 } },\n  { $limit: 1 },\n  { $lookup: { from: \"users\", localField: \"_id\", foreignField: \"_id\", as: \"user\" } },\n  { $unwind: \"$user\" },\n  { $project: {  } }\n])",
        hints: ["Group + sort + limit finds the top reviewer id.", "Join users, project name: \"$user.name\", count: 1, _id: 0."],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$user_id\", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }, { $limit: 1 }, { $lookup: { from: \"users\", localField: \"_id\", foreignField: \"_id\", as: \"user\" } }, { $unwind: \"$user\" }, { $project: { _id: 0, name: \"$user.name\", count: 1 } } ])",
        explanation: "Reduce first (group→sort→limit), then join only the survivor. Doing the join last keeps it efficient." },
      { id: "lk10", title: "Premium reviewers' names", difficulty: 3, ordered: true,
        prompt: "List the names of premium users who have written at least one review. Group reviews by user_id, join users, keep membership \"premium\", project name (no _id), sort by name ascending.",
        starter: "db.reviews.aggregate([\n  { $group: { _id: \"$user_id\" } },\n  { $lookup: { from: \"users\", localField: \"_id\", foreignField: \"_id\", as: \"user\" } },\n  { $unwind: \"$user\" },\n  { $match: { \"user.membership\": \"premium\" } },\n  { $project: {  } },\n  { $sort: { name: 1 } }\n])",
        hints: ["Grouping by user_id dedupes reviewers.", "Match \"user.membership\": \"premium\", project name: \"$user.name\", _id: 0."],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$user_id\" } }, { $lookup: { from: \"users\", localField: \"_id\", foreignField: \"_id\", as: \"user\" } }, { $unwind: \"$user\" }, { $match: { \"user.membership\": \"premium\" } }, { $project: { _id: 0, name: \"$user.name\" } }, { $sort: { name: 1 } } ])",
        explanation: "You can $match on joined fields after unwinding — filtering the parent by a property of the joined document." }
    ]
  },

  {
    id: "agg-advanced",
    name: "10 · Advanced Aggregation",
    blurb: "$addFields, $bucket, $facet, $switch, $replaceRoot and multi-stage pipelines.",
    concept: {
      summary: "Compose expressions and specialized stages to build reports, categorize data, and reshape documents into exactly the form you need.",
      points: [
        "$addFields (alias $set) adds or updates fields while KEEPING the rest — unlike $project.",
        "$bucket groups a numeric field into ranges [inclusive, exclusive) with a catch-all default.",
        "$facet runs several sub-pipelines over the SAME input for multi-part reports/dashboards.",
        "$switch is if / else-if / else; $cond is a compact ternary.",
        "$replaceRoot promotes an embedded document to the top level.",
        "Array expressions: $size, $slice, $arrayElemAt, $map, $filter, $reduce."
      ],
      syntax: [
        { code: "{ $addFields: { totalAwards: { $add: [\"$awards.wins\", \"$awards.nominations\"] } } }", note: "augment" },
        { code: "{ $bucket: { groupBy: \"$rating\", boundaries: [8, 8.5, 9, 9.6], default: \"other\", output: { count: { $sum: 1 } } } }", note: "histogram" },
        { code: "{ $switch: { branches: [ { case: { $gte: [\"$rating\", 9] }, then: \"Masterpiece\" } ], default: \"Good\" } }", note: "if/else" }
      ],
      tip: "Derive a grouping key with arithmetic ($subtract, $mod) then $group on it to build custom buckets — e.g. group movies by decade."
    },
    challenges: [
      { id: "ad1", title: "Add then rank", difficulty: 3, ordered: true,
        prompt: "Add a field totalAwards = awards.wins + awards.nominations, then return { title, totalAwards } for the top 5, sorted by totalAwards descending.",
        starter: "db.movies.aggregate([\n  { $addFields: { totalAwards: {  } } },\n  { $sort: { totalAwards: -1 } },\n  { $project: { _id: 0, title: 1, totalAwards: 1 } },\n  { $limit: 5 }\n])",
        hints: ["$addFields keeps existing fields and adds new ones.", "{ $add: [\"$awards.wins\", \"$awards.nominations\"] }"],
        solution: "db.movies.aggregate([ { $addFields: { totalAwards: { $add: [\"$awards.wins\", \"$awards.nominations\"] } } }, { $sort: { totalAwards: -1 } }, { $project: { _id: 0, title: 1, totalAwards: 1 } }, { $limit: 5 } ])",
        explanation: "$addFields (alias $set) augments documents without dropping fields, unlike $project. Great for computing something you then sort on." },
      { id: "ad2", title: "Bucket by rating", difficulty: 3, ordered: true,
        prompt: "Bucket movies by rating into boundaries [8, 8.5, 9, 9.6] with a default \"other\", counting each bucket as \"count\".",
        starter: "db.movies.aggregate([\n  { $bucket: {\n      groupBy: \"$rating\",\n      boundaries: [8, 8.5, 9, 9.6],\n      default: \"other\",\n      output: { count: { $sum: 1 } }\n  } }\n])",
        hints: ["Boundaries are [inclusive, exclusive) ranges.", "output defines accumulators per bucket."],
        solution: "db.movies.aggregate([ { $bucket: { groupBy: \"$rating\", boundaries: [8, 8.5, 9, 9.6], default: \"other\", output: { count: { $sum: 1 } } } } ])",
        explanation: "$bucket groups a numeric field into ranges. Each boundary pair is a bucket [lower, upper); values outside all ranges land in default." },
      { id: "ad3", title: "Two reports at once", difficulty: 3,
        prompt: "Use $facet to produce two outputs in one pass: \"byType\" = count per type (sorted by _id asc), and \"topRated\" = the top 3 movies as { title, rating } sorted by rating desc.",
        starter: "db.movies.aggregate([\n  { $facet: {\n      byType: [ { $group: { _id: \"$type\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ],\n      topRated: [ { $sort: { rating: -1 } }, { $limit: 3 }, { $project: { _id: 0, title: 1, rating: 1 } } ]\n  } }\n])",
        hints: ["$facet runs multiple sub-pipelines over the same input.", "Each facet key maps to its own array of stages."],
        solution: "db.movies.aggregate([ { $facet: { byType: [ { $group: { _id: \"$type\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ], topRated: [ { $sort: { rating: -1 } }, { $limit: 3 }, { $project: { _id: 0, title: 1, rating: 1 } } ] } } ])",
        explanation: "$facet computes several independent aggregations from one input stream — ideal for dashboards that need multiple summaries together." },
      { id: "ad4", title: "Tier with $switch", difficulty: 3, ordered: true,
        prompt: "For every movie return { title, tier } where tier is \"Masterpiece\" if rating >= 9, \"Excellent\" if rating >= 8.5, else \"Good\". Use $switch. Keep original order (no sort).",
        starter: "db.movies.aggregate([\n  { $project: { _id: 0, title: 1, tier: { $switch: {\n      branches: [\n        { case: { $gte: [\"$rating\", 9] }, then: \"Masterpiece\" },\n        { case: { $gte: [\"$rating\", 8.5] }, then: \"Excellent\" }\n      ],\n      default: \"Good\"\n  } } } }\n])",
        hints: ["$switch checks branches in order; first true wins.", "default handles the else case."],
        solution: "db.movies.aggregate([ { $project: { _id: 0, title: 1, tier: { $switch: { branches: [ { case: { $gte: [\"$rating\", 9] }, then: \"Masterpiece\" }, { case: { $gte: [\"$rating\", 8.5] }, then: \"Excellent\" } ], default: \"Good\" } } } } ])",
        explanation: "$switch is aggregation's if/else-if/else. Branches are evaluated top to bottom; the first matching case's `then` is used." },
      { id: "ad5", title: "Count by decade", difficulty: 3, ordered: true,
        prompt: "Group movies by decade and count them as \"count\". Compute decade = year - (year mod 10). Sort by _id (decade) ascending.",
        starter: "db.movies.aggregate([\n  { $project: { decade: { $subtract: [\"$year\", { $mod: [\"$year\", 10] }] } } },\n  { $group: { _id: \"$decade\", count: { $sum: 1 } } },\n  { $sort: { _id: 1 } }\n])",
        hints: ["$mod gives the remainder; subtract it to floor to the decade.", "Then group by the computed decade."],
        solution: "db.movies.aggregate([ { $project: { decade: { $subtract: [\"$year\", { $mod: [\"$year\", 10] }] } } }, { $group: { _id: \"$decade\", count: { $sum: 1 } } }, { $sort: { _id: 1 } } ])",
        explanation: "Deriving a grouping key with arithmetic ($subtract, $mod) then grouping on it is how you build custom histograms." },
      { id: "ad6", title: "Promote a sub-document", difficulty: 3,
        prompt: "For movie _id 5, make its awards object the top-level document using $replaceRoot. (Result: [{ wins, nominations }].)",
        starter: "db.movies.aggregate([\n  { $match: { _id: 5 } },\n  { $replaceRoot: { newRoot: \"$awards\" } }\n])",
        hints: ["newRoot is an expression that becomes the whole document.", "Point it at \"$awards\"."],
        solution: "db.movies.aggregate([ { $match: { _id: 5 } }, { $replaceRoot: { newRoot: \"$awards\" } } ])",
        explanation: "$replaceRoot swaps the document for one of its embedded objects — handy for lifting nested data to the top level." },
      { id: "ad7", title: "Reliable genres", difficulty: 3, ordered: true,
        prompt: "Find genres with at least 3 movies and their average rating. Unwind genres, group (avgRating and count), keep count >= 3, sort by avgRating descending then _id ascending, return { _id, avgRating, count }.",
        starter: "db.movies.aggregate([\n  { $unwind: \"$genres\" },\n  { $group: { _id: \"$genres\", avgRating: { $avg: \"$rating\" }, count: { $sum: 1 } } },\n  { $match: {  } },\n  { $sort: { avgRating: -1, _id: 1 } }\n])",
        hints: ["Filter groups with a $match AFTER $group (like SQL HAVING).", "{ count: { $gte: 3 } }"],
        solution: "db.movies.aggregate([ { $unwind: \"$genres\" }, { $group: { _id: \"$genres\", avgRating: { $avg: \"$rating\" }, count: { $sum: 1 } } }, { $match: { count: { $gte: 3 } } }, { $sort: { avgRating: -1, _id: 1 } } ])",
        explanation: "A $match after $group filters on aggregated values — MongoDB's equivalent of SQL's HAVING clause." },
      { id: "ad8", title: "Average reviews per movie", difficulty: 3,
        prompt: "Compute the average number of reviews per reviewed movie. Group reviews by movie_id (count each), then group again (_id null) averaging those counts as \"avgReviews\".",
        starter: "db.reviews.aggregate([\n  { $group: { _id: \"$movie_id\", count: { $sum: 1 } } },\n  { $group: { _id: null, avgReviews: {  } } }\n])",
        hints: ["The second group averages the first group's count.", "avgReviews: { $avg: \"$count\" }"],
        solution: "db.reviews.aggregate([ { $group: { _id: \"$movie_id\", count: { $sum: 1 } } }, { $group: { _id: null, avgReviews: { $avg: \"$count\" } } } ])",
        explanation: "Two-level grouping computes an aggregate-of-an-aggregate: first per-movie counts, then the average across movies." },
      { id: "ad9", title: "A user's taste", difficulty: 3,
        prompt: "For user _id 101, return { name, avgFavRating } = the average rating of their favorite movies. Join favorites to movies, then compute $avg over the joined ratings.",
        starter: "db.users.aggregate([\n  { $match: { _id: 101 } },\n  { $lookup: { from: \"movies\", localField: \"favorites\", foreignField: \"_id\", as: \"favMovies\" } },\n  { $project: { _id: 0, name: 1, avgFavRating: {  } } }\n])",
        hints: ["$avg can take an array expression: { $avg: \"$favMovies.rating\" }.", "\"$favMovies.rating\" pulls the rating from each joined doc."],
        solution: "db.users.aggregate([ { $match: { _id: 101 } }, { $lookup: { from: \"movies\", localField: \"favorites\", foreignField: \"_id\", as: \"favMovies\" } }, { $project: { _id: 0, name: 1, avgFavRating: { $avg: \"$favMovies.rating\" } } } ])",
        explanation: "In expressions, \"$array.field\" yields an array of that field's values; $avg then reduces it — combining a join with an array accumulator." },
      { id: "ad10", title: "Array shaping with $slice", difficulty: 3,
        prompt: "For movie _id 2, return { title, castCount, firstTwoGenres } where castCount is the number of cast members and firstTwoGenres is the first 2 genres.",
        starter: "db.movies.aggregate([\n  { $match: { _id: 2 } },\n  { $project: { _id: 0, title: 1, castCount: {  }, firstTwoGenres: {  } } }\n])",
        hints: ["castCount: { $size: \"$cast\" }.", "firstTwoGenres: { $slice: [\"$genres\", 2] }"],
        solution: "db.movies.aggregate([ { $match: { _id: 2 } }, { $project: { _id: 0, title: 1, castCount: { $size: \"$cast\" }, firstTwoGenres: { $slice: [\"$genres\", 2] } } } ])",
        explanation: "$size and the $slice expression let you measure and trim arrays inside a projection — the finishing touches of document shaping." }
    ]
  }
];
